### PR TITLE
A bunch of improvements

### LINKED ISSUE #62: fsnotify-0.2.1 test suite failure
Citing from http://hydra.cryp.to/build/1109590/log/raw:

```
Running 1 test suites...
Test suite test: RUNNING...
Tests
  Native
    Non-recursive
      Right here
        new file:                OK (0.56s)
        modify file:             FAIL (0.52s)
          Unexpected number of events.
            Expected: [Modified "/tmp/nix-build-haskell-fsnotify-0.2.1.drv-0/fsnotify-0.2.1/testdir/test.2380/testfile"]
            Actual: []
        delete file:             OK (0.50s)
        directories are ignored: OK (0.50s)
      In a subdirectory
        new file:                OK (0.50s)
        modify file:             OK (0.50s)
        delete file:             OK (0.50s)
        directories are ignored: OK (0.50s)
    Recursive
      Right here
        new file:                OK (0.54s)
        modify file:             OK (0.50s)
        delete file:             OK (0.50s)
        directories are ignored: OK (0.50s)
      In a subdirectory
        new file:                OK (0.50s)
        modify file:             OK (0.50s)
        delete file:             OK (0.50s)
        directories are ignored: OK (0.51s)
  Polling
    Non-recursive
      Right here
        new file:                OK (2.01s)
        modify file:             OK (2.00s)
        delete file:             OK (2.00s)
        directories are ignored: OK (2.00s)
      In a subdirectory
        new file:                OK (2.00s)
        modify file:             OK (2.00s)
        delete file:             OK (2.00s)
        directories are ignored: OK (2.00s)
    Recursive
      Right here
        new file:                OK (2.00s)
        modify file:             OK (2.00s)
        delete file:             OK (2.00s)
        directories are ignored: OK (2.00s)
      In a subdirectory
        new file:                OK (2.01s)
        modify file:             OK (2.01s)
        delete file:             OK (2.00s)
        directories are ignored: OK (2.00s)

1 out of 32 tests failed (40.29s)
Test suite test: FAIL
```

### LINKED ISSUE #67: `watchTree*` and creating new subdirectories
New subdirectories aren't immediately watched:

``` Haskell
#!/usr/bin/env stack
-- stack --resolver lts-7.4 --install-ghc runghc --package fsnotify --package directory --package temporary

import Control.Concurrent
import System.FSNotify
import System.FilePath
import System.Directory
import System.IO.Temp

main = 
  withSystemTempDirectory "fsnotify" $ \baseDir -> 
  withManager $ \mgr -> do
    _ <- watchTree mgr baseDir (const True) print
    writeFile (baseDir </> "file.txt") "whuzza"
    let childDir = baseDir </> "child"
    createDirectoryIfMissing True childDir
    -- threadDelay (10*1000)
    writeFile (childDir </> "child.txt") "whoop"
    threadDelay (1000*1000)
```

This prints only one line, instead of the expected two when that line is uncommented.

Also, this works as expected on OS X, but not on my Linux VM.

### PR DESCRIPTION
**Pull request by thomasjm**
Hi,

I've been giving this library some love for a while and was wondering if you would be interesting in merging this stuff back. Changes include

-- Detect directory creation/deletion (addresses #71)
-- Test suites passing on Travis/Appveyor on Windows, Linux, and Mac and test stability improved (should fix #62)
-- Improve a race condition when adding watches on Linux (because adding the watch takes some amount of time, it can miss files created while the watch was being created) (should fix #67)
-- Make things more sane on Mac, where FSEvents flags can be unpredictable (the situation in #69 is significantly improved as well as #36).
-- I believe issue #66 is fixed also.

This is a big collection of changes, so I'm open to feedback about what you want to do with it. A couple other notes:

-- There's a breaking API change; `Event`s now have an `isDirectory` flag, so `Added FilePath UTCTime` becomes `Added FilePath UTCTime Boolean`
-- On Windows I needed to adjust the flags being passed to `ReadDirectoryChangesW`, so I modified the `win32-notify` module so flags can be passed directly. That module is currently a git submodule in my branch. (Honestly I think it should just be copied into `hfsnotify`; it's only 2 files.)

Best,
Tom

### CODE REVIEW

**Comment by feuerbach** [comment]
Hey Tom, thanks for your work.

Unfortunately, there doesn't seem to be any active maintainers to review your code.

However, the package does need a new maintainer. Would you be willing to become one?

**Comment by thomasjm** [comment]
Hi @feuerbach -- yes! I'd be happy to.

**Comment by feuerbach** [comment]
Great! I already invited you as a committer to this github org. If you let me know your hackage username, I'll also grant you the upload rights.

**Comment by thomasjm** [comment]
Thanks -- Hackage username is `thomasjm`

**Comment by feuerbach** [comment]
Done!

**Comment by thomasjm** [comment]
Sweet, I'll turn this PR into a new major version release soon

**Pull request merged**
